name: SmokeTest

on:
  push:
    branches:
  workflow_dispatch:

jobs:
  # Tests the google_test_installer
  UnitTest_Installer:
    strategy:
      max-parallel: 2
      matrix:
#        platform: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        platform: ['ubuntu-latest']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout VCS
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Unit Test
        run: python -B -m unittest --verbose
        working-directory: google_test_installer

  # Tests GoogleTest installation
  UnitTest_Installation:
    needs: UnitTest_Installer
    strategy:
      max-parallel: 2
      matrix:
        platform: ['ubuntu-latest', 'windows-latest', 'macos-latest']
#        platform: ['windows-latest', 'macos-latest']
#        googletest-version: ['release-1.12.0', 'v1.14.0']
        googletest-version: ['release-1.12.0']
#        build-type: ['Release', 'Debug']
        build-type: ['Release']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout VCS
        uses: actions/checkout@v6

      ##################################################
      # Setup Environment
      ##################################################
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      ##################################################
      # Test
      ##################################################
      - name: Setup GoogleTest
        uses: ./
        with:
          tag: ${{ matrix.googletest-version }}
          build-type: ${{ matrix.build-type }}
          loglevel: 'DEBUG'

      - name: Verify Installation
        if: (runner.os == 'Linux') || (runner.os == 'macOs')
        run:    |
                if [ -f /usr/local/include/gtest/gtest.h ]; then
                    echo gtest/gtest.h is found.
                else
                    echo gtest/gtest.h is NOT found. Installation does not seem to work.
                    exit 1
                fi

      - name: Verify Installation
        if: runner.os == 'Windows'
        run:    |
                if ( Test-Path -Path "${env:USERPROFILE}\include\gtest\gtest.h" -PathType leaf )
                {
                    echo gtest/gtest.h is found.
                }
                else
                {
                    echo gtest/gtest.h is NOT found. Installation does not seem to work.
                    exit 1
                }

  IntegrationTest_Typical:
    needs: UnitTest_Installation
    strategy:
      max-parallel: 2
      matrix:
        platform: ['ubuntu-latest', 'windows-latest', 'macos-latest']
#        platform: ['windows-latest', 'macos-latest']
#        googletest-version: ['release-1.12.0', 'v1.14.0']
        googletest-version: ['release-1.12.0']
#        build-type: ['Release', 'Debug']
        build-type: ['Release']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout VCS
        uses: actions/checkout@v6

      ##################################################
      # Setup Environment
      ##################################################
      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup GoogleTest
        uses: ./
        with:
          tag: ${{ matrix.googletest-version }}
          build-type: ${{ matrix.build-type }}
          loglevel: 'DEBUG'

      ##################################################
      # Build
      ##################################################
      - name: Build
        if: (runner.os == 'Linux') || (runner.os == 'macOs')
        run: ./do_build.sh

      - name: Build
        if: runner.os == 'Windows'
        run: .\do_build.bat

      ##################################################
      # Lint
      ##################################################
      - name: Lint
        if: (runner.os == 'Linux') || (runner.os == 'macOs')
        run: ./do_lint.sh

      - name: Lint
        if: runner.os == 'Windows'
        run: .\do_lint.bat

      ##################################################
      # Test
      ##################################################
      - name: Test
        if: (runner.os == 'Linux') || (runner.os == 'macOs')
        run: ./do_test.sh

      - name: Test
        if: runner.os == 'Windows'
        run: .\do_test.bat

  # A test case that following directories are already exist.
  # - ${env:USERPROFILE}\bin
  # - ${env:USERPROFILE}\include
  # - ${env:USERPROFILE}\lib
  IntegrationTest_Misc:
    needs: UnitTest_Installation
    runs-on: windows-latest
    steps:
      - name: Checkout VCS
        uses: actions/checkout@v6

      ##################################################
      # Setup Environment
      ##################################################
      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Test Case
        run:    |
                mkdir "${env:USERPROFILE}\bin"
                mkdir "${env:USERPROFILE}\include"
                mkdir "${env:USERPROFILE}\lib"

      - name: Setup GoogleTest
        uses: ./
        with:
          tag: v1.14.0
          build-type: Release
          loglevel: DEBUG

      ##################################################
      # Build
      ##################################################
      - name: Build
        run: .\do_build.bat
